<!doctype html>
<html class="no-js" lang="en">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php wp_head(); ?> 

	<!-- <script> // documentation on this?
		var url = document.location.href;
		jQuery(document).ready(function() {
		//copy profile name to account name during registration
		if (url.indexOf("register/") >= 0) {
			jQuery('label[for=signup_username],#signup_username').css('display','none');
			jQuery('#field_1').blur(function(){
				jQuery("#signup_username").val(jQuery("#field_1").val());
			});
		}
		});
	</script> -->

	<!-- analytics -->
	<!-- <script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-12917302-6', 'auto');
		ga('send', 'pageview');
	</script> -->

	<!-- recaptcha -->
	<!-- <script src='https://www.google.com/recaptcha/api.js'></script> -->

	</head>
	<body>

		<!-- facebook -->
		<!-- <div id="fb-root"></div>
		<script>(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=163256807043192";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script> -->

	<!-- canvas wrappers -->
	<!-- <div class="off-canvas-wrapper"> -->
		<!-- <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper> -->

			<!-- this is the off canvas aka small menu -->
			<div id="minimenu" class="hide-for-print">
				<?php if ( has_custom_logo() ) { ?>
					<div class="site-logo"><?php the_custom_logo(); ?></div>
					<span class="screen-reader"><?php echo get_bloginfo( 'name' ); ?></span>
				<?php } else { ?>
					<h2><?php $blog_info = get_bloginfo( 'name' ); ?></h2>
				<?php } ?>
				<ul class="vertical menu">
					<?php if ( is_user_logged_in() ) {
						$current_user = wp_get_current_user();
						$current_login = $current_user->user_login; ?>
						<li>
							<h2 class="seconds">
								Welcome back <?php echo $current_login; ?>
							</h2>
						</li>
					<?php }
					?>
					<li><h2><a href=" php echo home_url(); ?>">Home</a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/about"><?php echo (get_page_by_title('About')->post_title); ?> Us</a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/order"><?php echo (get_page_by_title('Order')->post_title); ?></a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/contact"><?php echo (get_page_by_title('Contact Us')->post_title); ?></a></h2></li>
					<!-- <li><h2><a href=" php echo home_url(); ?>/booking"> php echo (get_page_by_title('Booking Form')->post_title); ?></a></h2></li> keep this removed -->
					<li><h2><a href=" php echo home_url(); ?>/beef"><?php echo (get_page_by_title('Beef')->post_title); ?></a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/pig"><?php echo (get_page_by_title('Pig')->post_title); ?></a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/deer"><?php echo (get_page_by_title('Deer')->post_title); ?></a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/sheep"><?php echo (get_page_by_title('Sheep')->post_title); ?></a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/alpaca-llama">Alpaca / Llama</a></h2></li>
					<li><h2><a href=" php echo home_url(); ?>/small-goods"><?php echo (get_page_by_title('Small Goods')->post_title); ?></a></h2></li>
					<li><?php
						if ( is_user_logged_in() ) { ?>

							<a href=" php echo home_url(); ?>/logout" class="button drop">logout</a>

						<?php } else { ?>
							<h2>Login</h2>  

							 <?php wp_login_form(); ?>

							<a href=" php echo home_url(); ?>/?page_id= php echo (get_page_by_title('register')->ID); ?>" class="button drop">Sign Up</a>

						<?php } ?>
					</li>
				</ul>
			</div>

			<!--  this is the in canvas -->
			<!-- <div class="off-canvas-content"> -->

				<!-- top bar remove this while im working on putting everything back together -->
				<section class="top-bar hide-for-print">
					<?php if ( is_user_logged_in() ) { ?>
						<div>
							<p>Welcome back,<?php echo $current_user->display_name; ?></p>
							<a href="<?php echo home_url(); ?>/view-profile">View Previous Orders</a>
						</div>
						<button href=" php echo home_url(); ?>/logout" class="">logout</button><!-- this should be a button -->
					<?php } else { ?>
						<div class="top-bar--together">
							<p>Hey, Your currently not logged in.</p>
							<button href=" php echo home_url(); ?>/login" class="hide-for-large">LOG IN</button><!-- button might be to a pop up? I hate those but this is generated by a click -->

							<!-- <div class="show-for-large"> show for the right size but large will do for now -->
								<!-- php
									$side_log = array (
										'form_id'        => 'side_log',
										'label_username' => 'email',
									); 
									wp_login_form( $side_log );
								?>
							</div> -->

							<button href="<?php echo home_url(); ?>/?page_id=<?php echo (get_page_by_title('register')->ID); ?>" class="">Sign Up</button>
							<!-- why would a customer sign up should go here -->
						</div>
					<?php } ?>
					<!-- show for either login state -->
					<button href=" php echo home_url(); ?>/contact" class=""><?php echo (get_page_by_title('Contact Us')->post_title); ?></button>
				</section>

				<header class="hide-for-print">
					<div class="top-background-image hide-for-print">
						<picture>
							<source srcset="<?php echo get_template_directory_uri(); ?>/img/iStock_000051038948_large.jpg" media="(min-width: 1440px)">
							<source srcset="<?php echo get_template_directory_uri(); ?>/img/iStock_000051038948_medium.jpg" media="(min-width: 640px)">
							<img src="<?php echo get_template_directory_uri(); ?>/img/iStock_000051038948_small.jpg">
						</picture>
					</div>
					<!-- logo wordpress default config -->
					<?php if ( has_custom_logo() ) { ?>
						<div class="site-logo"><?php the_custom_logo(); ?></div>
						<span class="screen-reader"><?php echo get_bloginfo( 'name' ); ?></span>
					<?php } else { ?>
						<?php $blog_info = get_bloginfo( 'name' ); ?>
					<?php } ?>

					<!-- small nav --> 
					<div class="small-nav hide-for-print"> <!-- being top level of the grid makes the button want to be full height -->
						<button onclick="touchMenu()">Menu</button>
						<!-- <button onclick="window.location.href = '#minimenu'">Menu</button>toggle off canvas -->
					</div>
				</header>

				<!-- medium up nav -->
				<nav id="mediummenu" class="show-for-medium hide-for-print"> <!-- medium up nav -->
					<?php wp_nav_menu( array(
						'theme_location' => 'primary',
						// 'menu_id'        => 'top-menu',
					) ); ?>
					<?php wp_nav_menu( array(
						'theme_location' => 'secondary',
						// 'menu_id'        => 'top-menu',
					) ); ?>


					<div class="flagbanner">
						<div class="flagbuttonbanner medium-12 columns">
							<ul class="menu expanded medium-up-menu a2">
								<li><a href="<?php echo home_url(); ?>">Home</a></li>
								<li><a href="<?php echo home_url(); ?>/about"><?php echo (get_page_by_title('About')->post_title); ?> Us</a></li>
								<li><a href="<?php echo home_url(); ?>/order"><?php echo (get_page_by_title('Order')->post_title); ?></a></li>
								<li><a href="<?php echo home_url(); ?>/contact"><?php echo (get_page_by_title('Contact Us')->post_title); ?></a></li>
							</ul>

							<ul class="menu expanded medium-up-menu a2">
								<li><a href="<?php echo home_url(); ?>/beef"><?php echo (get_page_by_title('Beef')->post_title); ?></a></li>
								<li><a href="<?php echo home_url(); ?>/pig"><?php echo (get_page_by_title('Pig')->post_title); ?></a></li>
								<li><a href="<?php echo home_url(); ?>/deer"><?php echo (get_page_by_title('Deer')->post_title); ?></a></li>
								<li><a href="<?php echo home_url(); ?>/sheep"><?php echo (get_page_by_title('Sheep')->post_title); ?></a></li>
								<li><a href="<?php echo home_url(); ?>/alpaca-llama"><span class="keep-all">Alpaca&nbsp;/</span> Llama</a></li>
								<li><a href="<?php echo home_url(); ?>/small-goods"><?php echo (get_page_by_title('Small Goods')->post_title); ?></a></li>
							</ul>
						</div> <!-- .flagbuttonbanner -->
					</div> <!-- .flagbanner -->
				</nav>
